export const style = {
    container: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "space-between",
        minHeight: "100vh",
        backgroundColor: "#1abc9c",
        fontFamily: "'Roboto', sans-serif",
        boxSizing: "border-box",
        padding: "20px",
    },
    header: {
        textAlign: "center",
        marginBottom: "20px",
        backgroundColor: "#2c3e50",
        padding: "20px",
        borderRadius: "10px",
        boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)",
        color: "white",
        width: "100%",
    },
    heading: {
        fontSize: "3rem",
        fontWeight: "bold",
        marginBottom: "10px",
    },
    description: {
        fontSize: "1.2rem",
        fontWeight: "400",
        color: "#ecf0f1",
        marginTop: "0",
    },
    boardContainer: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
    },
    row: {
        display: "flex",
    },
    cell: {
        width: "60px",
        height: "60px",
        cursor: "pointer",
        transition: "all 0.3s ease",
        borderRadius: "8px",
        boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
        margin: "4px",
    },
    footer: {
        textAlign: "center",
        padding: "10px",
        backgroundColor: "#2c3e50",
        borderRadius: "10px",
        boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)",
        color: "white",
        position: "absolute",
        bottom: "20px",
        width: "calc(100% - 40px)",
    },
    footerText: {
        fontSize: "1rem",
        fontWeight: "400",
        margin: "0",
    },
};
