export const styles = {
    heroSection: {
        background: '#f0f4f8',
        padding: '20px',
        borderRadius: '10px',
        maxWidth: '900px',
        margin: 'auto',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    heading: {
        textAlign: 'center',
        fontSize: '32px',
        marginBottom: '20px',
        fontFamily: 'Arial, sans-serif',
    },
    addTaskContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        marginBottom: '20px',
    },
    input: {
        padding: '10px',
        border: '1px solid #ddd',
        borderRadius: '5px',
        fontSize: '16px',
    },
    addButton: {
        background: '#6c5ce7',
        color: '#fff',
        padding: '10px',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        fontSize: '16px',
        transition: 'background 0.3s',
    },
    taskList: {
        display: 'grid',
        gap: '15px',
    },
    taskItem: {
        background: '#fff',
        borderRadius: '10px',
        padding: '15px',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    taskContent: {
        flex: 1,
    },
    taskTitle: {
        fontSize: '20px',
        fontWeight: 'bold',
        marginBottom: '5px',
    },
    taskDescription: {
        fontSize: '14px',
        color: '#555',
    },
    taskDate: {
        fontSize: '12px',
        color: '#777',
        marginTop: '5px',
    },
    taskActions: {
        display: 'flex',
        gap: '10px',
        flexDirection: 'column',
        alignItems: 'flex-end',
    },
    markButton: {
        background: '#00b894',
        color: '#fff',
        padding: '8px 15px',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
    },
    removeButton: {
        background: '#d63031',
        color: '#fff',
        padding: '8px 15px',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
    },
};